apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-envs
type: Opaque
data:
  OAUTH_CLIENT_ID: NDQ1NDk3NTEzNjU1LWpxbnNiM2k3dGQwb2k4c3Fwa3ZwNzkzcThsYzZtN3ZlLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  OAUTH_KEY: R09DU1BYLXpIdERaemdQMkFJdk03VTFOQ3BDQTYwNVlHXzA=
  JWT_SECRET: Z2V0cmljaG9yZGlldHJ5aW5n
  DB_HOST: bXlzcWwubWlrci51cw==
  DB_PORT: MzMwNg==
  DB_USERNAME: aDUxMA==
  DB_PASSWORD: MEJCMF83Njg2MzM=
  DB_DATABASE: ZGJfaDUxMA==
  DOMAIN: aHR0cDovL2xvY2FsaG9zdDozMDAw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: bswitals/graderef
          env:
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: OAUTH_CLIENT_ID
                  optional: false
            - name: OAUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: OAUTH_KEY
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: JWT_SECRET
                  optional: false
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DB_HOST
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DB_PORT
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DB_USERNAME
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DB_PASSWORD
                  optional: false
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DB_DATABASE
                  optional: false
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: backend-envs
                  key: DOMAIN
                  optional: false