service: graderef-backend

configValidationMode: error

useDotenv: true

plugins:
  - serverless-plugin-warmup

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *)
      concurrency: 10
      verbose: true
      logRetentionInDays: 14
    outOfOfficeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 0-7 ? * MON-FRI *)
        - schedule: cron(0/5 18-23 ? * MON-FRI *)
        - schedule: cron(0/5 * ? * SAT-SUN *)
      concurrency: 1
      verbose: false
    testWarmer:
      enabled: false

provider:
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  name: aws
  runtime: nodejs16.x
  timeout: 900
  region: eu-west-1
  memorySize: 2048
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}
    DOMAIN: ${env:DOMAIN}
    SMS_API_KEY: ${env:SMS_API_KEY}
    SMS_PASSWORD: ${env:SMS_PASSWORD}
    SMS_NUMBER: ${env:SMS_NUMBER}
    SMS_SENDER: ${env:SMS_SENDER}
    AWS_BUCKET_GRADES: ${env:AWS_BUCKET_GRADES}
    AWS_BUCKET_MATCHES: ${env:AWS_BUCKET_MATCHES}

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
