name: Deploy-serverless

on:
  push:
    branches: ['feature-serverless']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: JWT_SECRET=test JWT_SECRET=test OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}} OAUTH_KEY=${{secrets.OAUTH_KEY}} DOMAIN=${{secrets.DOMAIN}} SMS_API_KEY=${{secrets.SMS_API_KEY}} SMS_PASSWORD=${{secrets.SMS_PASSWORD}} SMS_NUMBER=${{secrets.SMS_NUMBER}} SMS_SENDER=${{secrets.SMS_SENDER}} npm run test:e2e
  deploy:
    needs: test
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install NPM dependencies
        run: npm install

      - name: Deploy Lambda functions
        run: serverless deploy -s dev
        env:
         OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
         OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
         JWT_SECRET: ${{ secrets.JWT_SECRET }}
         DB_HOST: ${{ secrets.DB_HOST }}
         DB_PORT: ${{ secrets.DB_PORT }}
         DB_USERNAME: ${{ secrets.DB_USERNAME }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         DB_DATABASE: ${{ secrets.DB_DATABASE }}
         DOMAIN: ${{ secrets.DOMAIN }}
         SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
         SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
         SMS_NUMBER: ${{ secrets.SMS_NUMBER }}
         SMS_SENDER: ${{ secrets.SMS_SENDER }}