name: Deploy-serverless

on:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: JWT_SECRET=test JWT_SECRET=test OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}} OAUTH_KEY=${{secrets.OAUTH_KEY}} DOMAIN=${{secrets.DOMAIN}} SMS_API_KEY=${{secrets.SMS_API_KEY}} SMS_PASSWORD=${{secrets.SMS_PASSWORD}} SMS_NUMBER=${{secrets.SMS_NUMBER}} SMS_SENDER=${{secrets.SMS_SENDER}} npm run test:e2e
  deploy:
    needs: test
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
         OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
         JWT_SECRET: ${{ secrets.JWT_SECRET }}
         DB_HOST: ${{ secrets.DB_HOST }}
         DB_PORT: ${{ secrets.DB_PORT }}
         DB_USERNAME: ${{ secrets.DB_USERNAME }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         DB_DATABASE: ${{ secrets.DB_DATABASE }}
         DOMAIN: ${{ secrets.DOMAIN }}
         SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
         SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
         SMS_NUMBER: ${{ secrets.SMS_NUMBER }}
         SMS_SENDER: ${{ secrets.SMS_SENDER }}