name: Deploy

on:
  push:
    branches: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: JWT_SECRET=test JWT_SECRET=test OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}} OAUTH_KEY=${{secrets.OAUTH_KEY}} DOMAIN=${{secrets.DOMAIN}} SMS_API_KEY=${{secrets.SMS_API_KEY}} SMS_PASSWORD=${{secrets.SMS_PASSWORD}} SMS_NUMBER=${{secrets.SMS_NUMBER}} SMS_SENDER=${{secrets.SMS_SENDER}} npm run test:e2e
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bswitals/graderef:latest
  update-VPS-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update image inside VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -q --filter ancestor=bswitals/graderef )
            docker pull bswitals/graderef
            docker run -e OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}} -e OAUTH_KEY=${{secrets.OAUTH_KEY}} -e SMS_API_KEY=${{secrets.SMS_API_KEY}} -e SMS_PASSWORD=${{secrets.SMS_PASSWORD}} -e SMS_NUMBER=${{secrets.SMS_NUMBER}} -e SMS_SENDER=${{secrets.SMS_SENDER}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e DB_DATABASE=${{secrets.DB_DATABASE}} -e DOMAIN=${{secrets.DOMAIN}} -d -p 3000:3000 bswitals/graderef
