name: E2E Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  prtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: JWT_SECRET=test SMS_API_KEY=${{secrets.SMS_API_KEY}} SMS_PASSWORD=${{secrets.SMS_PASSWORD}} SMS_NUMBER=${{secrets.SMS_NUMBER}} SMS_SENDER=${{secrets.SMS_SENDER}} npm run test:e2e
