name: E2E Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  prtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: JWT_SECRET=test OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}} OAUTH_KEY=${{secrets.OAUTH_KEY}} DOMAIN=${{secrets.DOMAIN}} SMS_API_KEY=${{secrets.SMS_API_KEY}} SMS_PASSWORD=${{secrets.SMS_PASSWORD}} SMS_NUMBER=${{SMS_NUMBER}} npm run test:e2e
